[project]
name = "spectools"
authors = [
    {name = "R. Michael Jennings", email = "robermjenningsjr@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
version = "0.1.0"
dependencies = []

[tool.setuptools]
packages = ["spectools"]
